spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cloud:

server:
  port: 8081

mybatis:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰映射
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tSedx96czDbg6tGmk3a
    accessKeySecret:
    bucketName: web-cjng

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
