spring:
  datasource:
    # 数据库连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: 123456
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cloud:

# 服务配置
server:
  port: 8081

mybatis:
  configuration:
    # 日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰映射
    map-underscore-to-camel-case: true

# 阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tSedx96czDbg6tGmk3a
    accessKeySecret: W3nGnN6fmbs0fHfa8XXL2g4FABmDg8
    bucketName: web-cjng

# 日志配置
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
